### ISSUE TITLE
Umbraco 10.4.0 backoffice wont start when not in debug after installing Workflow

### ISSUE THREAD

**Issue by pgregorynz** [umbraco/Umbraco.Workflow.Issues#10]
We installed Umbraco Workflow 10.0.0 on Umbraco 10.4.0 via Nuget.  All works fine when running out of Visual Studio in debug, but as soon as we are running in production (debug off) the backoffice of Umbraco will not load.  It seems to be a bundling error of some kind relating to Workflow and Smidge as the files smidge creates are throwing 500 errors.

After uninstalling Workflow and deploying again the error is resolved.

Reproduction
------------

1. On umbraco 10.4.0 site install workflow
2. Runs fine in dev
3. Run in production mode (debug disabled) 500 errors appear in console for

/sb/umbraco-backoffice-js.js.vXXXXXXXXXXXXXXX

and 

/sb/umbraco-backoffice-css.css.vXXXXXXXXXXXXX

### Expected result

Site runs in production mode and Workflow also works.

### Actual result

Broken back office (white screen on nothingness)

**Comment by nathanwoulfe** [comment]
Hey @pgregorynz long time no chat, hope you're doing well.

This is interesting, as Workflow shouldn't be touched by Smidge - it's explicitly opting out of the backoffice bundling mechanism, in the interest of avoiding overly large single bundles. I'll have a dig and see what I can uncover.

**Comment by pgregorynz** [comment]
Thanks for looking into this.   It has been a long time.

We were on an earlier version of 10 and installing Workflow also caused an Umbraco upgrade to 10.4.0. Not sure if this caused it?


________________________________

**Comment by nathanwoulfe** [comment]
I was able to reproduce this - installed fresh Umbraco 10.0, installed Workflow 10, Umbraco upgrades to 10.4 (Workflow 10 has a min Umbraco version of 10.4), backoffice fails to load due to the Smidge 500 error.

What I found though was the 500 is due to missing Umbraco UI library files, which shipped in 10.3. These are missing because while installing Workflow 10 upgrades Umbraco to 10.4, that process doesn't modify the package reference in the project file, so we're left with missing assets. Manually updating the reference to `Version="10.4.0"` and rebuilding seems to fix it.

At least, that's what I've seen happening just now. Will run the same steps again to confirm.
