### ISSUE TITLE
Settings Flow Type

### ISSUE THREAD

**Issue by MichaelBeever** [umbraco/Umbraco.Workflow.Issues#15]
Hello,

I am trying to setup the tool in such a way that if an approver submits a change to a page they are unable to approve it.

Is this possible?

**Comment by MichaelBeever** [comment]
Hi This is what I have set and it still sends. Does this just stop notifcations?

**Comment by nathanwoulfe** [comment]
I'll need to have look, but sounds like that could be a bug - if we exclude the original editor, they should not receive notifications and should not be able to action the pending workflow.

**Comment by MichaelBeever** [comment]
Assuming I have set everything up correct.

I have two users at the moment.

A content creater who is in the Writer group to login and an Approver who is in the editor group to login.

Then both of these groups are in the approval groups tab in the workflow.

Is that correct?

**Comment by MichaelBeever** [comment]
![image](https://user-images.githubusercontent.com/72510812/229713707-2e874bb9-80a8-45bf-8e0d-2277af0f4e07.png)

![image](https://user-images.githubusercontent.com/72510812/229713791-20078ecb-f187-4324-978b-54967443fb03.png)

Does this look correct?

**Comment by nathanwoulfe** [comment]
That looks ok, but is a very minimal setup - one approval group, with one user, for all content on the site (as the permissions set on Home will be inherited). Based on that example, if the MBApprove user make a change and submits for approval, they won't be able to approve the change as they will be excluded from the workflow, which will leave you with a workflow in limbo with no approver.

The exclude flow type really should be used with groups >1 member, so that pending tasks can still be approved if there is a user excluded from the task (due to initiating the current workflow).

I have changes coming in 10.2/11/2 which add a new licensed feature for setting approval thresholds, part of that change includes a revision of the flow types to make sure they work as expected.

**Comment by MichaelBeever** [comment]
Hi, totally agree a minimal setup, this is intential as I am wanting to confirm proof of concept.

If MBApporve submits they are able to approve.

**Comment by nathanwoulfe** [comment]
Looks like the exclude flow isn't working correctly - they should not be able to approve (which will leave the workflow stuck with no approver). 

Will be fixed in 10.2, which is a couple of weeks away.

**Comment by MichaelBeever** [comment]
Ok great will keep an eye on it, thanks for your help

**Comment by nathanwoulfe** [comment]
No worries, there will be an RC for the minor, so if you feel like kicking the tyres when that's available...

**Comment by nathanwoulfe** [comment]
Hey @MichaelBeever just to confirm - this is fixed and will be part of 10.2 and 11.2
