### ISSUE TITLE
When using a test license doesn't allow to add an approval group

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#2]
Added an approval group without any license. After impersonating a test license, doesn't show the previously created approval group as well as doesn't allow to add a new approval group. Throws the attached error.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Added an approval group without any license. After impersonating a test license, doesn't show the previously created approval group as well as doesn't allow to add a new approval group. Throws the attached error.

### Specifics

Using Umbraco CMS version 11.0.0-rc4, Workflow v11.0.0-rc2
![image](https://user-images.githubusercontent.com/82437098/201874210-395aa4aa-1e6a-44f6-b80f-0c7843273f8e.png)

### Steps to reproduce

1. Create an approval group without a license.
2. Update appsettings.json file to enable a test license.
3. Run the app.
4. Go to approval groups, the previously created approval group is no longer available.
5. Create a new approval group.
6. Throws an error.

### Actual result
https://user-images.githubusercontent.com/82437098/201874887-6d61d4e2-ee14-4dd8-affa-3d64ca87433e.mp4

**Comment by nathanwoulfe** [comment]
Hi @eshanrnh this will be fixed in the next RC - issue was related to the licensing changes, where impersonating a license was setting the license type to Trial rather than Licensed, but still setting the correct group limits (ie -1 when impersonating). That then meant that getting groups was limiting to -1, hence nothing returned in the UI. I suspect some of the other issues you've raised will be related to this too.
