### ISSUE TITLE
Exclusion inheritance doesn't see to work

### ISSUE THREAD

**Issue by AussieInSeattle** [umbraco/Umbraco.Workflow.Issues#22]
We have setup workflow on v8 and are finding that the exclusion functionality is not working as expected - we have the following content tree structure:
-Home
--Your Government

We have a workflow setup on "Home" and we have the "Your Government" node selected under Workflow > Settings > Exclude nodes however the Your Government node (and its children) is still showing the workflow tab, whereas they shouldn't as that node is in the Exclude list - seems the "inheritance" is over-riding the exclusion where-as we were expecting it to be around the other way?

---
_This item has been added to our backlog AB#30334_

**Comment by nathanwoulfe** [comment]
Hey @AussieInSeattle - I've had a look at this in 2.1.12 on Umbraco 8.16, and can't reproduce (video below). I've excluded the child node, set a workflow on the parent, and am seeing the workflow app removed on the child, which is the expected behaviour.

Is there something else configuration-wise that could be causing the issue? Wondering if this is a node with no content app, which was the other part of our discussion last week...

https://github.com/umbraco/Umbraco.Workflow.Issues/assets/3248070/a397e635-ec8d-471b-bbba-e2fd1000ea97

**Comment by nathanwoulfe** [comment]
Ping @AussieInSeattle, where you at, Matt?
