### ISSUE TITLE
Fixed review dates

### ISSUE THREAD

**Issue by LeaTark** [umbraco/Umbraco.Workflow.Issues#31]
I think there needs to be an option of fixed dates along with a review frequency.
Frequency is not always the best measure of when content should be reviewed.
e.g. If we have some time-sensitive content that needs to change in 30 days, we could set a period of 30 days and a reminder the day before.
However, if we add a new content item to the review list next week then all periods are recalculated and we lose the first reminder.

**Comment by nathanwoulfe** [comment]
Hi @LeaTark, you're correct in that this looks buggy - it shouldn't regen dates when saving if a date already exists. Ideally should have the option somewhere to regenerate all as well. I'll get it fixed.

**Comment by nathanwoulfe** [comment]
Hey @LeaTark, I've had a look into this one, and will be updating with the following:
 - changing the default review period will not modify any node-level configuration
 - setting detail review period to 0 will remove all nodes from review (other than those with explicit configuration)
 - adds option when saving config to generate reviews relative to the current date or the last published date for each node

I appreciate this doesn't address the suggestion of allowing a fixed review date rather than a time period, but it does fix the issue with config erroneously being deleted, so will go some way to solving your issue. I'm happy to look into a fixed date review, but will need to do that in a future minor release.

**Comment by nathanwoulfe** [comment]
RC for the next release is on the way to Nuget, with a fix for this issue 🚀
