### ISSUE TITLE
Implicit flow not working as expected

### ISSUE THREAD

**Issue by anthony-3chillies** [umbraco/Umbraco.Workflow.Issues#33]
Trying to achieve something with Workflow, and think this would be the way to do it. But am struggling with an issue.

We have 2 types of users:

- Writers:  Should be able to review other writers content (effectively flow type exclude).
- Editors: Should be able to approve writers content but also need to be able self publish (effectively flow type implicit)

Reproduction
------------

## Flow type
Implicit:  auto-approves steps where the author is a member of the approving group.

### Writers

- Writer 1
- Writer 2
- Writer 3

### Editors

- Editor 1
- Editor 2

### Writer 1 Approval Group
- Writer 2
- Writer 3
- Editors

### Writer 2 Approval Group
- Writer 1
- Writer 3
- Editors

### Writer 3 Approval Group
- Writer 1
- Writer 2 
- Editors

## Steps to reproduce

- Login as Writer 3
- Create new page
- Add comment and request approval

## Expected result
Approval would move to the Writer 3 Approval group as Writer 3 is a member of both Writer 1 and Writer 2 Approval Groups.

## Actual result
Approval waits on Writer 1 group and progresses through all groups.

Wrap up
---------
To wrap up, I think this is the only way to achieve what I'm looking for using Workflow, unless I've missed something.
It would be nice if this could be achieved in a less convoluted way e.g set Flow type per user/group.

**Comment by nathanwoulfe** [comment]
Hey @anthony-3chillies could you share the configuration from the node and the Workflow + Umbraco versions. As far as I'm aware, implicit flow works correctly, but could be configuration-related...

At the moment, it's not possible to set the flow type per group, and I'm not sure would make sense to do so. If you need editors to self-publish, try setting Extend Permissions to true, which will keep the user's default actions rather than replacing with Workflow's Request (un)Publish button. This way editors can chose to use Workflow, or just Save and Publish.
