### ISSUE TITLE
Cannot reject an active workflow. activePermissions is undefined.

### ISSUE THREAD

**Issue by Fjellvang** [umbraco/Umbraco.Workflow.Issues#51]
When attempting to reject an active workflow nothing happens. Inspecting the console reveals that no activePermissions is set, hence the javascript fails.

Using Umbraco `13.0.3` and Workflow `13.0.1` 

Reproduction
------------

1. Install Umbraco 13.0.3 with the starter template.
2. Install Workflow 13.0.1
3. Create two approval groups
    - Proof Readers
    - Publishers
4. Create two new users and attach them to each group.
5. Add two groups to the new node approval flow.
6. Create a new blog post and send to approval.
7. Attempt to reject the workflow from any user.

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/9480541/e945a7e6-f0cd-4087-a2d8-648eb340a779)

**Comment by Fjellvang** [comment]
I just tested on Umbraco `12.3.6` and workflow `12.2.2`. Same issue.

I simply installed the 2 packages, including the starter pack. This time i made a single group and only added the default admin user. If i attempt to reject my own publish i get the same issue

**Comment by nathanwoulfe** [comment]
Hey @Fjellvang, I'll add this to the current sprint to investigate. Meanwhile, I'd appreciate if you could confirm this only happens when using the new-node workflow, and rejecting tasks where the configuration is set on the node works as expected.

Looking at the screenshot, the `Group has no member` message in the bottom-right Workflow activity component looks problematic and will likely point to the problem (group members are not being populated, so no permissions available, so no rejection).

**Comment by Fjellvang** [comment]
Hey @nathanwoulfe .

Im not sure why it reported that the group has no member, as i tested with both assigning an umbraco user group and assigning the members explicitly: 
![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/9480541/2d745ace-f8c9-4b42-8bcd-eade33268efd)


I only tested without license initially using the "new node flow". If i approve the new node flow, and then request new changes choosing an approval group manually, then that group can correctly decline changes.

**Comment by nathanwoulfe** [comment]
Heya @Fjellvang, this one is fixed and building for release now. Will be on Nuget shortly 🚀
