### ISSUE TITLE
Workflow publishes unwanted language versions of a page

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco.Workflow.Issues#52]
Workflow publishes unwanted language versions of a page. Say I have English, Italian, French and Arabic in a site. A page ois published in English and Italian. 

When I Request Publish, it publishes these two variants of a page. I then accidentally publish a French variant as well, but then unpublish it. Now when I Request Publish Invariant, on Approval, I will publish all three language variants, even the unpublished French version. 

Nowhere in the process do we get the option to select which variants I'm requesting to publish, or am approving. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Specifics

DorchesterCollection.com 
V 11.3.1 
U 11.4.2

### Expected result
I'm expecting a prompt to ask me which languages I'm sending for approval, so I don't have to send Just this one twice, but a single request to publish two variants... Once a language variant has been published, it would also be good to go back to the original state when it wasn't yet published and Request Publish is not sending it for publish on approval

### Actual result
Currently all variants that have once been published are published

---
_This item has been added to our backlog AB#36934_

**Comment by nathanwoulfe** [comment]
Weird, I'm sure I added a comment...

This definitely needs fixing - it's been overlooked since day one. We cater for individual variants, invariant, and per-variant workflows, but don't have the option for publishing a subset of variants. Will need some thought around how to best make that work (ie what happens if a variant doesn't have a workflow configured? Should it be selectable, should it use the default language workflow).

Probably warrants a UI review too - the existing toggles can probably be replaced with something more elegant.

Thanks for letting us know, I'll post back here with any updates 🚀

**Comment by nathanwoulfe** [comment]
Hey @gabador-mof, just wanted to check in - I'm looking at this in our current sprint, but realised your reported version is 11, which is EOL (for both Umbraco and Workflow). Any plans at your end to update to 12/13?

**Comment by gabador-mof** [comment]
Hi Nathan, yes, we will upgrade to v12 soon. Feel free to release a fix to
a V12 version or upwards...

Thanks,
Gabor

**Comment by nathanwoulfe** [comment]
@gabador-mof @krebil, I think the solution to both your issues (this one and #53) will be achieved through the same changes - the split-view issues is due to content nodes only showing the content app, making the workflow app inaccessible so requesting publish is also not possible. Similarly, for this task, we need better UI for managing selecting variants.
To solve both, I think I need to introduce a modal for requesting publish, similar to Umbraco's save/save-and-publish overlays, to separate the action from the content app (which is still initialised and running, but not accessible from the UI).

Apologies for taking so long to look into these, but I guess the benefit is a single solution for two problems 🚀

**Comment by nathanwoulfe** [comment]
Reworking the request approval UI, will look something like this...
https://github.com/umbraco/Umbraco.Workflow.Issues/assets/3248070/c99b5316-570c-4cc1-ace1-16b14804db02

**Comment by gabador-mof** [comment]
Hi Nathan, thanks, I think that will solve the problem! Thanks for your
work on this
Gabor

**Comment by nathanwoulfe** [comment]
@gabador-mof this is available now in the latest patch releases (10.3.7, 12.2.4, 13.0.3) 🚀
