### ISSUE TITLE
How to disable Umbraco Workflow from Content Delivery API?

### ISSUE THREAD

**Issue by fbpenalosa** [umbraco/Umbraco.Workflow.Issues#58]
How to disable Umbraco Workflow from Content Delivery API?

Reproduction
------------

I'm simply trying to disable/hide the Umbraco Workflow from Content delivery API but I can't seem to find in docus on how to do it:

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/160117578/eecbf7a8-3cd3-4876-b7db-a0b6c5135171)

### Bug summary

Simply need to disable Umbraco Workflow from Content Delivery API

### Specifics

Umbraco CMS 12.3.6
Umbraco Workflow 12.2.4

**Comment by nathanwoulfe** [comment]
Workflow isn't associated with Content Delivery API, but does provide Swagger documentation (as do other products and packages). These are all backoffice endpoints, requiring authentication, so much more aligned with Management rather than Content API. 

The Swagger UI is only available in non-prod environments, so not sure what there is to gain by removing it, or how to go about doing so.

Unless I'm entirely missing your point?

**Comment by fbpenalosa** [comment]
@nathanwoulfe Thank you for the quick response. That actually covered my question. My original intent was to make sure that we only expose Content Delivery API and not the Workflow API. So as long as Swagger is not accessible in prod instances, I think we're good.

**Comment by nathanwoulfe** [comment]
All Workflow API endpoints require an authenticated user with backoffice access, so Postman etc wouldn't be able to query these. Just like the broader CMS backoffice API, it's secured by the BackofficeAccess authorization policy.

**Comment by fbpenalosa** [comment]
@nathanwoulfe  Thank you for the clarifications.
