### ISSUE TITLE
Clicking on a User/User Group does not open configuration pane

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco.Workflow.Issues#75]
When you click on a user/user group, the Edit configuration pane used to open, but now nothing happens. There is no way to edit the User/user group configuration/permissions.

Reproduction
------------

**Approval Groups:**
1. Go to Workflow -> Approval Groups
2. Click on a User in the Group members column.

**Settings:**

1. Go to Workflow -> Settings.
2. Click on a User Group in the New node approval flow section.

---
_This item has been added to our backlog AB#42672_

**Comment by nathanwoulfe** [comment]
Heya @eshanrnh this is partially intentional, partially oversight on my part. Intentional in that we don't want to allow editing groups from the content section (ie when on a node, in the workflow configuration, we don't allow editing groups from here). 

Similarly, from the approval groups dashboard, the only action should be to edit the group, as the UI would get overwhelming if the group members and permissions were all links. I'll fix up the link/hover state on the other columns - that's a CMS default that I need to override.

In the edit view for a group, it makes sense to be able to edit the permissions, so I'm adding overlays to allow this (opening either the content node or the workflow settings for editing the document type approvals). In future I want to investigate editing the document type approvals in a modal directly from the group, but that requires some larger changes as the doc type approvals are currently part of the settings data, and can't be edited without the settings workspace context.

**Comment by eshanrnh** [comment]
Hey @nathanwoulfe, it makes sense. I think if you just remove the links and hover action from the non-editable/read-only items, it won't look like a design flaw 🙌

**Comment by nathanwoulfe** [comment]
Hey @eshanrnh there are a couple of places where I'm using the CMS components and can't modify the internal styles. I've tidied up where I can, but will need to raise it with Team Bellissima to see if we can expose some styling hooks.

Otherwise, the changes we discussed above are in 14.0.2 🚀
