### ISSUE TITLE
Requesting a new scheduled publication time doesn't work

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco.Workflow.Issues#80]
If an editor requests a page for publish setting a scheduled time for the publish and later on requests a new publication time, the new publication time will be shown, but when the time has passed, the page won't be published and the publication time will revert to the originally set time.

Reproduction
------------

Seen on Umbraco 13.4.1 and Workflow 13.2.0+faab5a3

1. As an editor, request publish with a "Publish on" date set.
2. Get the request approved.
3. Request another publish with a new "Publish on" date set.
4. Get the request approved.
5. Wait for the time to pass the second date.

### Expected result

I would expect that the second "Publish on" date would be the date for the publication

### Actual result

The page is not published at the time of the second "Publish on" date. Instead, the page now shows the first "Publish on" date again.

The only way to alter the "Publish on" date is by having an administrator go and remove it through the normal Schedule menu.

---
_This item has been added to our backlog AB#44405_

**Comment by nathanwoulfe** [comment]
Hey @sniffdk this is an interesting one as it could be seen to be the expected behaviour - when submitting the second workflow, the content is already scheduled, so should we be resetting the scheduled date, keeping the first, or not allowing scheduling at all, or not allowing scheduling earlier than the existing scheduled date? Absolutely not a question for you to answer, but something we need to consider at our end.

**Comment by nathanwoulfe** [comment]
Patches out now, this one should be working correctly now 🚀

**Comment by sniffdk** [comment]
@nathanwoulfe which solution did you decide on here? 😄

**Comment by nathanwoulfe** [comment]
Works per your expected result - the scheduled date will be set to the date in the second workflow. Issue was caused by not clearing the content schedule when setting the date, so would always be using the earliest value. Now when a workflow is scheduled we ensure that the date is the only value for release/expire, so when the scheduler runs, there's not a queue of dates (which should never happen).

It does mean it would be possible to approve a scheduled workflow, start a second scheduled workflow, and if the first date passes before the second workflow is approved, the first changes wouldn't be published as the node is still in a workflow. I don't see any realistic way around that, as scheduling has never allowed stacking versions for future publication, it simply publishes the latest version of a document at a given date.

**Comment by sniffdk** [comment]
@nathanwoulfe Thanks, that makes sense 👍 
And yeah, the problem here is Umbraco not having a way to publish a specific version, but only always the newest version at publish time. 

This way still makes more sense from an editing perspective I believe, so thanks for patching it up 😊👍
