### ISSUE TITLE
Workflow will publish the latest version of content, not the actual approved version

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco.Workflow.Issues#84]
If an editor sends a page to publication through the workflow and sets a publication time, after the request has been approved it is possible for the editor to make further changes, save them and have those unapproved changes published on the selected publication date completely bypassing the workflow.

Reproduction
------------

Editor:
1. Make a change to the content and save it.
2. Request publish and set a publication date, eg. 5 minutes out.

Approver:
1. Approve the publish request.

Editor:
1. Make changes to the content and save it.

Now, when the page is published at the set time, all the unapproved changes will get published as well.
Congratulations, you have now completely bypassed the core functionality of the Workflow package 😅 🙈

I assume this happens because Umbraco just publishes the latest saved content version, as that is the normal behavior and Workflow simply offloads the publishing responsibility to the build-in scheduler.
I guess the problem arises primarily on scheduled publications because Workflow considers the publication workflow completed as soon as it is approved, thereby releasing the edit lock on the page.

Instead, however, Workflow should make sure that only the actual approved version of the content is published or simply cancel the approved workflow if changes are made between approval and publication.

I realize that might be easier said than done, but at the current state the workflow package is basically unusable if you want to approve changes for publication ahead of time and actually care about approving 100% of the content that gets published.

This was tested on Umbraco 13.4.1 and Workflow 13.2.0+faab5a3

---
_This item has been added to our backlog AB#44875_

**Comment by nathanwoulfe** [comment]
Hi @sniffdk, you're right in that Workflow relies on the CMS's scheduler for scheduled publishing, so what you're seeing is the same as what can be done without Workflow (content is scheduled for a future date, but subsequent changes can be added to the node which will be published on the scheduled date).

It might be possible to have Workflow intercept the scheduled publish, check that current version matches the workflow-approved version, and rollback if different, then publish, but that would also result in data loss if an editor has saved changes on the document (which would otherwise be published at the scheduled date, so could be argued that it's not really data loss as the changes shouldn't go live anyway 🤷 )

Might make better sense to leave the content locked once the workflow is completed, until the scheduled date passes. IMO, that's how the CMS should handle scheduling to prevent this issue entirely (scheduled content should be immutable, shouldn't it?)

Will need to have a think about the best way to manage this. It also relates to the planned work for release sets, so might be addressed in that feature too.

**Comment by sniffdk** [comment]
In an ideal world, Umbraco would support publishing a specific content version instead of the just newest one.
As long as that is not possible, I would think that having the ability to lock the content until the publish is done would be a more acceptable way of doing it.
Then, if you need to make changes before publish, you would need to cancel the workflow, make changes, save and start the approval process over.

It's not the most fluent way of working, but it is definitely the more secure way, when approvals are important, I think 👍

**Comment by nathanwoulfe** [comment]
@sniffdk I have a feature release next week to resolve this. Works like so:
- introduces new setting for controlling scheduled content locks, where the options are:
  - None: current behavior
  - Workflow: locks scheduled documents where the schedule was set in a workflow approval
  - All: locks all scheduled content
- locked documents can not be edited until the scheduled date passes (and the pending changes are published)
- Workflow administrators can unlock the document from the editor view (new button in the footer)
- unlocking gives the option to publish the pending changes or keep as draft

**Comment by nathanwoulfe** [comment]
@sniffdk this landed in the latest Workflow minors, released this week. Works as per my previous comment, and ensures approved scheduled content can not be modified between approval and publication.

**Comment by sniffdk** [comment]
@nathanwoulfe Thanks a lot for this, will check it out in detail as soon as possible 👍 🙏
