### ISSUE TITLE
Workflow issue in when used with uMarketingSuite

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco.Workflow.Issues#86]
Putting "personalization variants" from uMS into workflow creates an empty workflow item that you cannot progress or remove.

### Specifics

Umbraco v13.4.0
Workflow v13.0.7
uMarketingSuite
Load balanced on Azure

### Steps to reproduce

Select the personalization variants, these are usually all selected by default if its on the default language. Press the "Request publish..." button.

### Expected result

This depends on the UX. But generally I would expect personalization variants to enter workflow in the same way culture variants do

### Actual result

Empty workflow item created that you cannot progress or remove.

**Comment by nathanwoulfe** [comment]
Hey @drummerboy46 segments are handled properly in the latest releases - please try upgrading to Workflow 13.3.0 and let me know if the problem is resolved. 

Segments are a little tricky in that publishing one publishes all segments for the culture, so selecting one segment for workflow approval will publish any other segments belonging to that culture. Which does make sense - while cultures are independent, segments are not (eg an A/B test needs two segments, so publishing all ensures that these exist at render time). The UI in latest Workflow versions has been updated to reflect this.
